services:
  - type: web
    name: miray-photography
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
    autoDeploy: true
    healthCheckPath: /
    
  # Static files serving (opsiyonel - Express zaten static dosyaları serve ediyor)
  staticPublishPath: ./public 